name = "GpuOptim"
uuid = "90cd4a59-3550-4b37-b31b-5de4fae66293"
authors = ["Hector Peeters <hector.peeters@gmail.com>"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Metatheory = "e9d8d322-4543-424a-9be4-0cc815abe26c"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BenchmarkTools = "1.5.0"
DataStructures = "0.18.18"
Metatheory = "2.0.2"
TermInterface = "0.3.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
